services:
  blog:
    image: node:24-alpine
    container_name: ricardo-blog
    working_dir: /app
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
    environment:
      PNPM_HOME: /pnpm
      PATH: /pnpm:$PATH
    command: >
      sh -c "
      corepack enable &&
      pnpm install &&
      pnpm dev --host 0.0.0.0
      "

volumes:
  node_modules:
  pnpm_store:
